#!/usr/bin/env python3

import asyncio

from src.cli.app import ConsoleApplication


def main():

    app = ConsoleApplication()

    asyncio.run(
        app.start()
    )

if __name__ == "__main__":
    main()