#!/bin/python3
# Library import
import asyncio
from src.core import AgentCore

# Classes definition
class AgentApp:
    def __init__(self):
        self.core = None
        self.running = None

    async def start(self) -> bool:
        self.core = AgentCore()
        
        await self.core.start()
        
        self.running = True
        return True

    async def stop(self) -> bool:
        if not self.running or not self.core: return True

        await self.core.stop()
        self.running = False

        return True

# Entry-point
if __name__ == "__main__":
    agent = AgentApp()
    asyncio.run(
        agent.start()
    )